# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CommonProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
  pod 'Alamofire'

end
